AWSTemplateFormatVersion:  2010-09-09
Resources:
  #Create an Auto Scaling Group
  AutoScalingGroup:
    Type:  'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId:  !ImportValue MyLaunchTemplate
        Version:  1 # !Sub  ${!ImportValue MyLaunchTemplate}.LatestVersionNumber
      VPCZoneIdentifier:
      - !ImportValue SubnetA
      - !ImportValue SubnetB

#Scaling Policy
  ScalingPolicy:
    Type:  'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref AutoScalingGroup
      ScalingAdjustment: 1

# #Alarm for testing
#   CloudWatchAlarm:
#     Type:  'AWS::CloudWatch::Alarm'
#     Properties:
#       EvaluationPeriods:  '1'
#       Statistic:  Average
#       Threshold:  '50'
#       AlarmDescription:  Alarm  set  fo  50%  of  CPU  utilization
#       Period:  '60'
#       AlarmActions:
#       -  !Ref  ScalingPolicy
#       Namespace:  AWS/EC2
#       Dimensions:
#       -  Name:  AutoScalingGroupName
#       Value:
#       Ref:  AutoScalingGroup
#       ComparisonOperator:  GreaterThanThreshold
#       MetricName:  CPUUtilization