AWSTemplateFormatVersion: '2010-09-09'
Description: Create an IPv6-only VPC with 3 IPv6-only subnets

Parameters:
  VpcCidrBlock:
    Type: String
    Default: "fd00:10:20::/64"  # Update with your desired IPv6 CIDR block for the VPC
    Description: CIDR block for the IPv6 VPC

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      AssignIpv6AddressOnCreation: true