Parameters:
  EnvironmentName:
    Description: Environment name for the application dev/staging/production
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev
    
Resources:  
  StandardQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${EnvironmentName}-StandardQueue1"
      
      # Configuration ------------------

      DelaySeconds: 1                  # Should be between 0 seconds and 15 minutes. 
      VisibilityTimeout: 30             # Should be between 0 seconds and 12 hours.
      ReceiveMessageWaitTimeSeconds: 2  # Should be between 0 and 20 seconds. for Short vs Long polling configuration
      MessageRetentionPeriod: 86400     # Should be between 1 minute and 14 days.
      MaximumMessageSize: 2048          # Should be between 1 KB and 256 KB.

      # # Redrive Policy ------------------
      # RedrivePolicy:
      #   deadLetterTargetArn: arn:aws:sqs:us-east-1:418295706200:dev-DLQueue1
      #   maxReceiveCount: 3

  StandardQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: StandardQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: allow-sns-messages
          Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action: sqs:SendMessage
          Resource:
            Fn::GetAtt:
            - StandardQueue
            - Arn
          Condition:
            ArnEquals:
              aws:SourceArn:
                arn:aws:sns:us-east-1:418295706200:MySNSTopic

  # DLQueue:
  #   Type: AWS::SQS::Queue
  #   Properties:
  #     QueueName: !Sub "${EnvironmentName}-DLQueue1"
  #     RedriveAllowPolicy:
  #       redrivePermission: byQueue  # The allowed values are: allowAll, denyAll, byQueue
  #       sourceQueueArns:
  #       - arn:aws:sqs:us-east-1:418295706200:dev-StandardQueue1


  FIFOQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${EnvironmentName}-FIFOQueue1.fifo"
      
      # Configuration ------------------

      DelaySeconds: 1                   # Should be between 0 seconds and 15 minutes. 
      VisibilityTimeout: 30             # Should be between 0 seconds and 12 hours.
      ReceiveMessageWaitTimeSeconds: 2  # Should be between 0 and 20 seconds.
      MessageRetentionPeriod: 86400     # Should be between 1 minute and 14 days.
      MaximumMessageSize: 2048          # Should be between 1 KB and 256 KB.

      # FIFO queue settings ------------------
      FifoQueue: true
      ContentBasedDeduplication: true         # false
      DeduplicationScope: messageGroup        # Or queue
      FifoThroughputLimit: perMessageGroupId  # Or perQueue




Outputs:
  StandardQueueURL:
    Description: URL of the created StandardQueue
    Value:
      Ref: StandardQueue
  StandardQueueARN:
    Description: ARN of the created StandardQueue
    Value:
      Fn::GetAtt:
      - StandardQueue
      - Arn
  StandardQueueName:
    Description: Name of the created StandardQueue
    Value:
      Fn::GetAtt:
      - StandardQueue
      - QueueName

  FIFOQueueURL:
    Description: URL of the created SQS
    Value:
      Ref: FIFOQueue
  
  FIFOQueueARN:
    Description: ARN of the created SQS
    Value:
      Fn::GetAtt:
      - FIFOQueue
      - Arn
  FIFOQueueName:
    Description: Name of the created SQS
    Value:
      Fn::GetAtt:
      - FIFOQueue
      - QueueName

  # DLQueueURL:
  #   Description: URL of the created SQS
  #   Value:
  #     Ref: DLQueue
  
  # DLQueueARN:
  #   Description: ARN of the created SQS
  #   Value:
  #     Fn::GetAtt:
  #     - DLQueue
  #     - Arn
  # DLQueueName:
  #   Description: Name of the created SQS
  #   Value:
  #     Fn::GetAtt:
  #     - DLQueue
  #     - QueueName