Description: |
  AWS API Gatway with Lambda proxy integration
  https://www.moesif.com/blog/technical/api-development/Building-Rest-API-With-AWS-Gateway-And-Python/

Parameters:
  DeploymentBucketName:
    Description: My S3 Bucket Name
    Type: String
    Default: deployment-bucket-786x


Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: rest-api-with-lambda
      Handler: first-api.lambda_handler
      Role: !ImportValue LambdaExecutionRoleARN
      Runtime: python3.11
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: first-api.py.zip
      Timeout: 30
      MemorySize: 128