AWSTemplateFormatVersion: 2010-09-09
Description: IAM managed policies for developers

Resources:
  PoliciesOnDeveloper:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "PoliciesOnDeveloper"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - sqs:*
          - cloudformation:*
          - s3:*
          - s3-object-lambda:*
          Resource: "*"
        
        - Effect: Allow
          Action:
          - sns:ListTopics
          Resource: "*"

        - Effect: Allow
          Action: iam:*
          Resource: "*"
        
        - Effect: Allow
          Action: ec2:*
          Resource: "*"
        
        - Effect: Allow
          Action: 
          - ec2-instance-connect:*
          - ec2:CreateInstanceConnectEndpoint
          - ec2:CreateNetworkInterface
          - ec2:CreateTags
          - iam:CreateServiceLinkedRole
          Resource: "*"

        - Effect: Allow
          Action: 
          - cloudwatch:DescribeAlarms
          - cloudwatch:ListMetrics
          - cloudwatch:DescribeAlarmsForMetric
          - cloudwatch:GetMetricData
          Resource: "*"

        - Effect: Allow
          Action: 
          - elasticloadbalancing:DescribeTargetGroups
          - elasticloadbalancing:CreateTargetGroup
          - elasticloadbalancing:DescribeLoadBalancers
          - elasticloadbalancing:CreateLoadBalancer
          - elasticloadbalancing:AddTags
          - elasticloadbalancing:DescribeListeners
          - elasticloadbalancing:CreateListener
          - elasticloadbalancing:DeleteListener
          Resource: "*"

        - Effect: Allow
          Action: 
          - autoscaling:*
          Resource: "*"

        - Effect: Allow
          Action: 
          - q:PassRequest
          - q:SendMessage
          - q:StartConversation
          - q:GetConversation
          - q:ListConversations
          - q:*
          Resource: "*"

        - Effect: Allow
          Action: 
          - access-analyzer:*
          Resource: "*"

        - Effect: Allow
          Action: 
          - SNS:*
          Resource: "*"

        - Effect: Allow
          Action: 
          - cloudshell:*
          Resource: "*"
        
        - Effect: Allow
          Action: 
          - lambda:*
          Resource: "*"
        
        - Effect: Allow
          Action: 
          - logs:*
          Resource: "*"

        - Effect: Allow
          Action: 
          - logs:*
          Resource: "*"

        - Effect: Allow
          Action:
          - dynamodb:*
          - dax:*
          - application-autoscaling:DeleteScalingPolicy
          - application-autoscaling:DeregisterScalableTarget
          - application-autoscaling:DescribeScalableTargets
          - application-autoscaling:DescribeScalingActivities
          - application-autoscaling:DescribeScalingPolicies
          - application-autoscaling:PutScalingPolicy
          - application-autoscaling:RegisterScalableTarget
          - cloudwatch:DeleteAlarms
          - cloudwatch:DescribeAlarmHistory
          - cloudwatch:DescribeAlarms
          - cloudwatch:DescribeAlarmsForMetric
          - cloudwatch:GetMetricStatistics
          - cloudwatch:ListMetrics
          - cloudwatch:PutMetricAlarm
          - cloudwatch:GetMetricData
          - datapipeline:ActivatePipeline
          - datapipeline:CreatePipeline
          - datapipeline:DeletePipeline
          - datapipeline:DescribeObjects
          - datapipeline:DescribePipelines
          - datapipeline:GetPipelineDefinition
          - datapipeline:ListPipelines
          - datapipeline:PutPipelineDefinition
          - datapipeline:QueryObjects
          - ec2:DescribeVpcs
          - ec2:DescribeSubnets
          - ec2:DescribeSecurityGroups
          - iam:GetRole
          - iam:ListRoles
          - kms:DescribeKey
          - kms:ListAliases
          - sns:CreateTopic
          - sns:DeleteTopic
          - sns:ListSubscriptions
          - sns:ListSubscriptionsByTopic
          - sns:ListTopics
          - sns:Subscribe
          - sns:Unsubscribe
          - sns:SetTopicAttributes
          - lambda:CreateFunction
          - lambda:ListFunctions
          - lambda:ListEventSourceMappings
          - lambda:CreateEventSourceMapping
          - lambda:DeleteEventSourceMapping
          - lambda:GetFunctionConfiguration
          - lambda:DeleteFunction
          - resource-groups:ListGroups
          - resource-groups:ListGroupResources
          - resource-groups:GetGroup
          - resource-groups:GetGroupQuery
          - resource-groups:DeleteGroup
          - resource-groups:CreateGroup
          - tag:GetResources
          - kinesis:ListStreams
          - kinesis:DescribeStream
          - kinesis:DescribeStreamSummary
          Resource: "*"  



      Groups:
        - 'DeveloperGroup'

  # BucketAccessPolicy:
  #   Type: "AWS::IAM::Policy"
  #   Properties:
  #     PolicyName: "WebDataBucketPolicy"
  #     PolicyDocument:
  #       Statement:
  #         - Sid: WebDataBucketPolicy
  #           Effect: Allow
  #           Action: s3:*
  #           Resource: !Join 
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - !Ref WebDataBucket
  #               - /*
  #           Condition:
  #             StringEquals:
  #               aws:PrincipalTag/Developer: "SpecialDuty"
  #               aws:ResourceTag/Lifetime: Permanent





