AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template for Creating IAM Groups 

Resources:
 
  DeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DeveloperGroup
      Path: /
  
  CustomerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: CustomerGroup
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  
Outputs:

  DeveloperGroup:
    Description: Developer Group
    Value: !GetAtt DeveloperGroup.Arn

  CustomerGroup:
    Description: Customer or User Group
    Value: !GetAtt CustomerGroup.Arn
    


