AWSTemplateFormatVersion: 2010-09-09

Resources:
  SameRegionReplicationS3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CustomRoleSameRegionReplication 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
          Action: "sts:AssumeRole"

      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
              - s3:GetReplicationConfiguration
              - s3:ListBucket
              Resource:
              - arn:aws:s3:::events-k8gk754       #SOURCE-BUCKET
            - Effect: Allow
              Action:
              - s3:GetObjectVersionForReplication
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
              Resource:
              - arn:aws:s3:::events-k8gk754/*     #SOURCE-BUCKET
            - Effect: Allow
              Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicateTags
              Resource: arn:aws:s3:::events-k8gk754-dest/*   #DESTINATION-BUCKET