AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template for Creating IAM Users

Parameters:
  Admin1Password:
    Description: Enter the password for the User with Administrator privilege
    Type: String
    Default: Password123$
  
Resources:

  
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AdminGroup
      Path: /
      Policies:
        - PolicyName: "AdministratorAccessPolicies"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
              
              - Effect: Allow
                Action:
                - cloudformation:*
                - cloudformation:DescribeStacks
                Resource: "*"
              
              - Effect: "Allow"
                Action: 
                - sqs:*
                - cloudformation:*
                - s3:*
                - s3-object-lambda:*
                Resource: "*"
              - Effect: Allow
                Action:
                - iam:*
                Resource: "*"



          
  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: admin1
      LoginProfile:
        Password: !Ref Admin1Password
        PasswordResetRequired: false
      Path: /
      Groups:
        - !Ref AdminGroup


  PoliciesOnAdministrator:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "AdministratorAccessExplicitPolicies"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - billing:*
          Resource: "*"        
        - Effect: Allow
          Action:
          - sns:ListTopics
          Resource: "*"
        - Effect: Allow
          Action: iam:*
          Resource: "*"

      Groups:
        - !Ref AdminGroup

Outputs:
  Admin1:
    Description: admin1 User
    Value: !GetAtt AdminUser.Arn

