Parameters:
  DeploymentBucketName:
    Description: Deployment Bucket Name
    Type: String
    Default: deployment-bucket-20250329-xcdf

  BucketVersioning:
    Description: Versioning configuration for the bucket
    Type: String
    AllowedValues:
    - Suspended
    - Enabled
    Default: Suspended

Resources:

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DeploymentBucketName
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-DeploymentBucket' 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: !Ref BucketVersioning

  DeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Statement:
          - Sid: Statement-1
            Effect: Allow
            Action: 
            - s3:GetObject
            Principal: '*'
            Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref DeploymentBucket
              - /*

Outputs:
  DeploymentBucket:
     Description: The Deployment Bucket Arn
     Value: !Sub '${DeploymentBucket.Arn}'
     Export: 
      Name: DeploymentBucket



      
