Parameters:
  EmailAdrs:
    Description: Enter Your Email Address.
    Type: String
    Default: "mail2mamud@gmail.com"
    
Resources:
  MySNStopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: MySNSTopic
      Subscription:
      - Protocol: email
        Endpoint: !Ref EmailAdrs

  MySNStopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: 
      - !Ref MySNStopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: SNS topic policy
          Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action:
          - SNS:Publish
          Resource: arn:aws:sns:us-east-1:418295706200:MySNSTopic
          Condition:
            ArnLike:
              aws:SourceArn: arn:aws:s3:::events-123x
            StringEquals:
              aws:SourceAccount: 418295706200


      



          






