AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for the DynamoDB
Parameters:
  EnvironmentName:
    Description: Environment name for the application dev/staging/production
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev
Resources:
  EventOrganizers:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "${EnvironmentName}-event-organizers"
      AttributeDefinitions:
        - AttributeName: OrgId
          AttributeType: S
        # - AttributeName: OragName
        #   AttributeType: S
        # - AttributeName: OragType
        #   AttributeType: S
        # - AttributeName: Addressline1
        #   AttributeType: S
        # - AttributeName: Addressline2
        #   AttributeType: S
        # - AttributeName: Addressline3
        #   AttributeType: S                                     
        # - AttributeName: PostalCode
        #   AttributeType: N
        # - AttributeName: Contact Person
        #   AttributeType: N
        # - AttributeName: Country Code1
        #   AttributeType: N          
        # - AttributeName: PhoneNo1
        #   AttributeType: N
        # - AttributeName: Country Code2
        #   AttributeType: N             
        # - AttributeName: PhoneNo2
        #   AttributeType: S
        # - AttributeName: EmailAddress
        #   AttributeType: S

      KeySchema:
        - AttributeName: OrgId
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


  Events:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "${EnvironmentName}-events"
      AttributeDefinitions:
        # - AttributeName: OrgId
        #   AttributeType: N
        # - AttributeName: Year
        #   AttributeType: S
        # - AttributeName: Month
        #   AttributeType: S
        # - AttributeName: EventName
        #   AttributeType: S
        - AttributeName: EventId
          AttributeType: N
        # - AttributeName: TemplateID
        #   AttributeType: N                                     
      KeySchema:
        - AttributeName: EventId
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  EventOrganizers:
    Value: !Ref EventOrganizers

  Events:
    Value: !Ref Events