name: Deploy Azure Functions

on:
  push:
    branches:
      - main
      - branch1
    paths:
      - 'Terraform/Azure/applications/**'

defaults:
  run:
    working-directory: ./Terraform/Azure/applications/function-apps1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CREDENTIALS     : ${{ secrets.AZURE_CREDENTIALS }}
      FUNCTIONAPP_NAME      : ${{ secrets.FUNCTIONAPP_NAME }}
      AZURE_RG              : ${{ secrets.AZURE_RG }}
      AZURE_SUBSCRIPTION_ID : ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Load secrets
      run: env | grep AZURE_

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
