name: Deploy Azure Functions

on:
  push:
    branches:
      - main
      - branch1
    paths:
      - 'Terraform/Azure/applications/**'

defaults:
  run:
    working-directory: ./Terraform/Azure/applications

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Load secrets
      id: secrets
      run: |
        echo "AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}" >> $GITHUB_ENV
        echo "FUNCTIONAPP_NAME=${{ secrets.FUNCTIONAPP_NAME }}" >> $GITHUB_ENV
        echo "AZURE_RG=${{ secrets.AZURE_RG }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
