name: Count Files

on:
  push:
    branches:
      - branch1  # Or the branch you want to monitor

jobs:
  count-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count files in a folder
        id: file_counter
        run: |
          # The "find" command will search for all files (-type f) in "my-folder".
          # The result is piped to "wc -l" which counts the lines, giving the total.
          FILE_COUNT=$(find /Terraform -type f | wc -l)
          
          # This command sets an output variable named "file_count"
          # that can be used by subsequent steps in the same job.
          echo "file_count=$FILE_COUNT" >> $GITHUB_OUTPUT

      - name: Display the count
        run: |
          echo "The folder 'my-folder' contains ${{ steps.file_counter.outputs.file_count }} files."