name: Terraform Snowflake Deployment

on:
  push:
    branches:
      - branch1
    paths:
      - 'Terraform/snowflake/**'


jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: eu74078.west-us-2
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ACCOUNTADMIN

    defaults:
      run:
        working-directory: Terraform/snowflake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # or your preferred version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # Uncomment the following block to enable auto-apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
