name: Terraform Snowflake Deployment

on:
  push:
    branches:
      - branch1
    paths:
      - 'Terraform/snowflake/**'


jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}


    defaults:
      run:
        working-directory: Terraform/snowflake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # or your preferred version

      - name: Debug Secrets
        run: |
          echo "Checking if secrets are available in the environment..."
          # The ::add-mask:: command redacts the value in the logs, but proves it's there.
          echo "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          echo "::add-mask::${{ secrets.SNOWFLAKE_USER }}"
          echo "::add-mask::${{ secrets.SNOWFLAKE_PASSWORD }}"
          echo "::add-mask::${{ secrets.SNOWFLAKE_ROLE }}"
          echo "Debug complete."

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan \
              -var="SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" \
              -var="SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" \
              -var="SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}" \
              -var="SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE }}"


      # Uncomment the following block to enable auto-apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
